version: '3.8'

services:
  authapp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: expense-tracker-auth-app
    ports:
      - "8091:8091"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/ExpenseTrackerDB
      SPRING_DATASOURCE_USERNAME: seb
      SPRING_DATASOURCE_PASSWORD: Jabba@0016
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    depends_on:
      - mysql
      - kafka

  userapp:
    build:
      context: ../ExpenseTracker_User/
      dockerfile: Dockerfile
    container_name: expense-tracker-user-app
    ports:
      - "8092:8092"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/ExpenseTrackerUserMicroServiceDB
      SPRING_DATASOURCE_USERNAME: seb
      SPRING_DATASOURCE_PASSWORD: Jabba@0016
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    depends_on:
      - mysql
      - kafka

  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ExpenseTrackerDB
      MYSQL_USER: seb
      MYSQL_PASSWORD: Jabba@0016
    volumes:
      - mysql_data:/var/lib/mysql

  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2182:2181"
    healthcheck:
      test: [ "CMD", "echo", "ruok", "|", "nc", "localhost", "2181" ]
      interval: 10s
      timeout: 5s
      retries: 5

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: kafka
    ports:
      - "9100:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
    depends_on:
      zookeeper:
        condition: service_healthy

  kafka2:
    image: confluentinc/cp-kafka:7.4.0
    container_name: kafka2
    ports:
      - "9101:9092"
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka2:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
    depends_on:
      - zookeeper

  kafka3:
    image: confluentinc/cp-kafka:7.4.0
    container_name: kafka3
    ports:
      - "9102:9092"
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka3:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
    depends_on:
      - zookeeper

volumes:
  mysql_data: